"""
Run KiloSort4 on the 2026-09-16 recording. Non-default settings per explicit
user request: Th_universal=9.0, Th_learned=8.0 (differs from the
20260910/20260901 sessions' Th_universal=9.2, Th_learned=7.0 -- deliberately
testing whether threshold choice affects detection of known-responsive units
on this session, per the user's stated purpose for this session). Everything
else left at KS4 default (confirmed via run_kilosort4_20260910.py's own
pattern -- do_CAR=True, invert_sign=False, save_preprocessed_copy=False,
clear_cache=False). Uses the probe map generated by make_probe_map.py for
this session (must be run first, from inside this session's .kilosort dir).
"""
from kilosort import run_kilosort
from kilosort.io import load_probe

SESSION_DIR = r"F:\Gil\Shamir\20260916_110311.rec\20260916_110311.kilosort"
PROBE_JSON = SESSION_DIR + r"\20260916_110311_custom_neuropixels_map.json"
DATA_FILE = SESSION_DIR + r"\20260916_110311.probe1.dat"

settings = {
    "n_chan_bin": 384,
    "fs": 30000.0,
    "Th_universal": 9.0,
    "Th_learned": 8.0,
}

probe = load_probe(PROBE_JSON)

run_kilosort(
    settings=settings,
    probe=probe,
    filename=DATA_FILE,
    data_dtype="int16",
    do_CAR=True,
    invert_sign=False,
    save_preprocessed_copy=False,
    clear_cache=False,
)
